samples: config/samples.tsv
project: CRC_Tissue
case_condition: Tumor
control_condition: Normal
discovery_sample_type: tissue

threads:
  sra: 6
  fastp: 6
  star: 6
  hisat2: 6
  featurecounts: 6
  lftp: 6
  stringtie: 6
  rmats: 6
  salmon: 6
  deseq2: 10
  kallisto: 10
  qualimap: 10
  modtect: 4
  wgcna: 4

resources:
  mem_mb:
    default: 4096
    sra: 4096
    fastp: 8192
    star_index: 102400
    star_align: 40960
    hisat2_index: 40960
    hisat2_align: 20480
    featurecounts: 8192
    salmon: 10240
    kallisto: 10240
    stringtie: 10240
    qualimap: 20480
    lftp: 10240
    annotation: 2048
    filtering: 10240
    faidx: 10240
    gffread: 4096
    picard: 8192
    gatk4: 16384
    rmats: 16384
    splicetools: 8192
    modtect: 8192
    deseq2: 8192
    wgcna: 16384
    clusterprofiler: 8192
    multiqc: 4096
    gffcompare: 4096

splicetools:
  fdr: 0.05
  control_tpm_threshold: 1
  case_tpm_threshold: 1

rmats:
  extra: " --variable-read-length --readLength 100 --novelSS --individual-counts "

fastp:
  extra: " -c "

star:
  extra: " --twopassMode Basic "
  index_extra: ""

hisat2:
  extra: " --dta "
  index_extra: ""

stringtie:
  extra: ""
  merge_extra: " -c 0 -F 0 -T 0 -i "

featurecounts:
  extra: " -p --countReadPairs -t exon -g gene_id "

gffcompare:
  extra: "  "

gffread:
  extra: ""

deg:
  padj: 0.00001
  log2fc: 2

reference:
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release (make sure to take one where snpeff data is available, check 'snpEff databases' output)
  release: 104
  # Genome build
  build: GRCh38
  select_contigs:
    - "1"
    - "2"
    - "3"
    - "4"
    - "5"
    - "6"
    - "7"
    - "8"
    - "9"
    - "10"
    - "11"
    - "12"
    - "13"
    - "14"
    - "15"
    - "16"
    - "17"
    - "18"
    - "19"
    - "20"
    - "21"
    - "22"
    - "X"

container:
  star: "docker://btrspg/star:2.7.11b"
  hisat2: "docker://btrspg/hisat2:2.2.1"
  fastp: "docker://btrspg/fastp:0.24.0"
  subread: "docker://btrspg/subread:2.1.1"
  qualimap: "docker://btrspg/qualimap:2.3"
  rmats: "docker://btrspg/rmatsturbo:4.3.0"
  gffcompare: "docker://btrspg/gffcompare:0.12.10"
  gffread: "docker://btrspg/gffread:0.12.7"
  python3: "docker://btrspg/python3:20251024"
  r: "docker://btrspg/rlan:20251027"
  clusterprofiler: "docker://btrspg/clusterprofiler:4.14.0"
  splicetools: "docker://btrspg/splicetools:c9fd38227fcdf43d1e08e919480372751f2ee5a4"
